"""Pure-python model layer for iprj Designer. No GUI imports allowed here."""

from .centerline import (
    centerline_to_lineals,
    lineals_to_centerlines,
    load_centerlines,
    save_centerlines,
)
from .coords import normalize_origin
from .iprj_io import (
    Background,
    Condition,
    EventZone,
    IgnoreZone,
    Lineal,
    Project,
    Sensor,
    TextLabel,
    load_iprj,
    save_iprj,
)
from .multifile import (
    BackgroundMatch,
    BackgroundMismatch,
    check_background_match,
    is_multifile,
    is_valid_pair,
    merge_pair,
    pair_paths,
    pair_role,
    split_project,
)
from .templates import (
    ApproachTemplate,
    DetectorSpec,
    Lane,
    PlacedDetector,
    expand_and_place,
    expand_template,
    load_template,
    place_detectors,
    save_template,
)

__all__ = [
    "Background",
    "Condition",
    "EventZone",
    "IgnoreZone",
    "Lineal",
    "Project",
    "Sensor",
    "TextLabel",
    "load_iprj",
    "normalize_origin",
    "save_iprj",
    "BackgroundMatch",
    "BackgroundMismatch",
    "check_background_match",
    "is_multifile",
    "is_valid_pair",
    "merge_pair",
    "pair_paths",
    "pair_role",
    "split_project",
    "centerline_to_lineals",
    "lineals_to_centerlines",
    "load_centerlines",
    "save_centerlines",
    "ApproachTemplate",
    "DetectorSpec",
    "Lane",
    "PlacedDetector",
    "expand_and_place",
    "expand_template",
    "load_template",
    "place_detectors",
    "save_template",
]
